modLoader="javafml"
loaderVersion="[32,)"
displayURL="https://suppergerrie2.com"
credits="The forge team for making forge!"
authors="suppergerrie2"

[[mods]]
modId="splayerskulldrops"
version="1.0"
displayName="Player Skull Drops"
description='''This is a mod that makes players drop their skull when killed by a charged creeper'''